#!/bin/bash

# SLOT Machine Code Signing Script
# Generated by Alera for Steve
# Pauses after each step for spacebar confirmation

set -e  # Exit on error

echo "=========================================="
echo "SLOT Machine Code Signing Automation"
echo "=========================================="
echo ""
echo "Press [ENTER] to proceed to each step..."
echo ""

# Function to wait for spacebar
wait_for_space() {
    echo ""
    echo "Step complete. Press [ENTER] to continue..."
    read -r
    echo ""
}

# Step 1: Change to working directory
echo "Step 1: Changing to /Users/steveleach/SlotMachineDMG/"
cd /Users/steveleach/SlotMachineDMG/
echo "Current directory: $(pwd)"
wait_for_space

# Step 2: Copy the app
echo "Step 2: Copying SlotMachine.app from build directory..."
cp -R "/Users/steveleach/Documents/Projects/SlotMachine_PcMac/Builds.nosync/MacOSX/build/Release/SlotMachine.app" .
echo "Copy complete."
wait_for_space

# Step 3: Strip attributes
echo "Step 3: Stripping extended attributes..."
xattr -rc SlotMachine.app
echo "Attributes stripped."
wait_for_space

# Step 4: Confirm no attributes
echo "Step 4: Verifying no attributes remain..."
echo "Running: xattr -lr SlotMachine.app"
xattr -lr SlotMachine.app || echo "(No attributes found - this is good!)"
wait_for_space

# Step 5: Rename
echo "Step 5: Renaming to 'SLOT Machine.app'..."
mv SlotMachine.app "SLOT Machine.app"
echo "Rename complete."
wait_for_space

# Step 6: Code sign the app
echo "Step 6: Code signing the app..."
echo "Running codesign with Developer ID..."
codesign --deep --force --options runtime \
    --sign "Developer ID Application: Steven Leach (M5X8C8C6SW)" \
    "SLOT Machine.app"
echo "Code signing complete."
wait_for_space

# Step 7: Zip the app
echo "Step 7: Creating zip archive..."
ditto -c -k --keepParent "SLOT Machine.app" "SLOT Machine.zip"
echo "Zip created: SLOT Machine.zip"
wait_for_space

# Step 8: Submit to Apple Notary
echo "Step 8: Submitting to Apple Notary Service..."
echo "This may take a few minutes..."
xcrun notarytool submit "SLOT Machine.zip" \
    --keychain-profile "notary-profile" \
    --wait
echo "Notary submission complete."
wait_for_space

# Step 9: Staple
echo "Step 9: Stapling notarization ticket..."
xcrun stapler staple "SLOT Machine.app"
echo "Staple complete."
wait_for_space

# Step 10: Verify
echo "Step 10: Verifying app signature..."
echo "Running: spctl -a -t exec -vv 'SLOT Machine.app'"
spctl -a -t exec -vv "SLOT Machine.app"
wait_for_space

# Step 11: Create DMG
echo "Step 11: Creating DMG..."
echo "This may take a moment..."
create-dmg \
    --volname "SLOT Machine" \
    --window-pos 200 120 \
    --window-size 600 400 \
    --icon-size 100 \
    --icon "SLOT Machine.app" 150 200 \
    --icon "Applications" 450 200 \
    --background dmg-background.png \
    --hide-extension "SLOT Machine.app" \
    SlotMachine-1.0.0.dmg \
    SlotMachineDMG/
echo "DMG created: SlotMachine-1.0.0.dmg"
wait_for_space

# Step 12: Sign DMG
echo "Step 12: Code signing the DMG..."
codesign --force --sign "Developer ID Application: Steven Leach (M5X8C8C6SW)" "SlotMachine-1.0.0.dmg"
echo "DMG signed."
wait_for_space

# Step 13: Verify DMG
echo "Step 13: Verifying DMG signature..."
echo "Running: codesign --verify --verbose=2 'SlotMachine-1.0.0.dmg'"
codesign --verify --verbose=2 "SlotMachine-1.0.0.dmg"
wait_for_space

echo ""
echo "=========================================="
echo "All steps complete! SLOT Machine is ready for distribution."
echo "=========================================="
echo ""
echo "Output files:"
echo "  - SLOT Machine.app (signed and notarized)"
echo "  - SLOT Machine.zip (for notary submission)"
echo "  - SlotMachine-1.0.0.dmg (signed DMG)"
echo ""
