; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{74E7ECF0-BE50-40BD-A61F-AD93B517B510}
AppName=S.L.O.T. Machine
AppVersion=1
;AppVerName=S.L.O.T. Machine
AppPublisher=Lone Pear Logic
DefaultDirName={autopf}\S.L.O.T. Machine
UninstallDisplayIcon={app}\SlotMachine.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=Slot Machine Setup
SetupIconFile=C:\Users\Stever Leach\source\repos\Slot-Machine-V2\Builds\VisualStudio2022\SlotMachine.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Stever Leach\source\repos\Slot-Machine-V2\Builds\VisualStudio2022\x64\Release\Standalone Plugin\SlotMachine.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Stever Leach\source\repos\Slot-Machine-V2\Builds\VisualStudio2022\x64\Release\VST3\SlotMachine.vst3\Contents\x86_64-win\SlotMachine.vst3"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Stever Leach\source\repos\Slot-Machine-V2\Resources\tutorialslotmachine.mp4"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\S.L.O.T. Machine"; Filename: "{app}\SlotMachine.exe"
Name: "{autodesktop}\S.L.O.T. Machine"; Filename: "{app}\SlotMachine.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\SlotMachine.exe"; Description: "{cm:LaunchProgram,S.L.O.T. Machine}"; Flags: nowait postinstall skipifsilent

